# layout: sidebar
#layout: stacked
layout: jekyll-theme-leap-day
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    forks: true
    projects:
    # - repo-name

# social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: alvarocafe
  # keybase: your_username
  # linkedin: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  # twitter: your_username
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username

 topics:
   - name: Wave problems
     web_url: https://github.com/alvarocafe/BEM_base
     image_url: images/4513PH03_16.jpg
   - name: Potential problems
     web_url: https://github.com/alvarocafe/PotConstTri3D
     image_url: images/4513PH03_16.jpg
